version: "3.9"

volumes:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-etc:
    name: foo-emqx-etc
  vol-emqx-log:
    name: foo-emqx-log

services:

  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    environment:
      TZ: "Europe/Lisbon"
      MONGO_INITDB_ROOT_USERNAME: "devuser"
      MONGO_INITDB_ROOT_PASSWORD: "devpassword"
    volumes:
      - /mongodata:/data/db
    ports:
      - 27017:27017

  emqx:
    container_name: emqx
    image: emqx/emqx:4.3.5
    restart: always
    ports:
      - 18083:18083
      - 18084:18084
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 8084:8084
      - 8085:8081

    volumes:
      - vol-emqx-data:/opt/emqx/data
      - vol-emqx-etc:/opt/emqx/etc
      - vol-emqx-log:/opt/emqx/log

    links:
      - mongo

    extra_hosts:
      - "localhost:192.168.1.57"

    environment:

      EMQX_NAME: iot
      EMQX_HOST: 127.0.0.1

      TZ: "Europe/Lisbon"

      # DEFAULT DASH PASS



      # dashboard.default_user.login = admin
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: "emqxdashpass"

      # DEFAULT APP SECRET
      EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "emqxsecret"

      # EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "${EMQX_DEFAULT_APPLICATION_SECRET}"




      EMQX_ALLOW_ANONYMOUS: "false"
      EMQX_NOMATCH: "deny"

      # MONGO CONNECTION
      EMQX_AUTH__MONGO__TYPE: single
      EMQX_AUTH__MONGO__SERVER: "mongo:27017"
      EMQX_AUTH__MONGO__POOL: 8

      EMQX_AUTH__MONGO__LOGIN: "devuser"
      EMQX_AUTH__MONGO__PASSWORD: "devpassword"
      EMQX_AUTH__MONGO__AUTH_SOURCE: admin

      EMQX_AUTH__MONGO__DATABASE: "iotgl"
      EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "emqxauthrules"

      EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
      EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"

      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
      EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
      EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"

      ## Enable ACL query.


      # ACL = Access control list
      EMQX_AUTH__MONGO__ACL_QUERY: "on"
      EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules"
      EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"

      EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo"

      #listener.tcp.external.max_connections
      EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000
